// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBllnEKhAuKAIiGgS0_BuqGJ0KIQUA5dSQ',
    appId: '1:285762515551:android:734931cfa5edada243e1ea',
    messagingSenderId: '285762515551',
    projectId: 'inmobiliariaarmandomarin',
    storageBucket: 'inmobiliariaarmandomarin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrzhEmUxbKt5A2YClSE3sLIUULWqxl7I4',
    appId: '1:285762515551:ios:75c1ac8cc60d811143e1ea',
    messagingSenderId: '285762515551',
    projectId: 'inmobiliariaarmandomarin',
    storageBucket: 'inmobiliariaarmandomarin.firebasestorage.app',
    iosClientId: '285762515551-tcdnlslh3u8m32r9ah3eb56fcjd2879d.apps.googleusercontent.com',
    iosBundleId: 'com.example.inmobiliariaapp',
  );
}
